services:
  pigeonwarden-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pigeonwarden-dev
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
    volumes:
      - .:/app
      - /dev:/dev
      - /opt/vc:/opt/vc
      - /run/udev:/run/udev:ro
    env_file:
      - .env.local
    environment:
      - USE_IP_FOR_REDIS_URI=1
      - UDEV=1
      - LD_LIBRARY_PATH=/opt/vc/lib
    command: ["python3", "-m", "pigeonwarden", "run", "dev"]

  pigeonwarden-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pigeonwarden-prod
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
    depends_on:
      - redis
    volumes:
      - .:/app
      - /dev:/dev
      - /opt/vc:/opt/vc
      - /run/udev:/run/udev:ro
    env_file:
      - .env.local
    environment:
      - USE_IP_FOR_REDIS_URI=1
      - UDEV=1
      - LD_LIBRARY_PATH=/opt/vc/lib
    command: ["python3", "-m", "pigeonwarden", "run", "deploy"]

  redis:
    image: redis:7
    container_name: pigeonwarden-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
