services:
  pigeonwarden-dev:
    build: .
    container_name: pigeonwarden-dev
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    env_file:
      - .env.local
    command: ["python", "-m", "pigeonwarden", "run", "dev"]

  pigeonwarden-prod:
    build: .
    container_name: pigeonwarden-prod
    ports:
      - "6969:6969"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env.local
    command: ["python", "-m", "pigeonwarden", "run", "deploy"]

  redis:
    image: redis:7
    container_name: pigeonwarden-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
