version: "3.9"

services:
  pigeonwarden-dev:
    build: .
    container_name: pigeonwarden-dev
    network_mode: "host"
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - .:/app
    env_file:
      - .env.local
    environment:
      - UDEV=1
    command: ["python3", "-m", "pigeonwarden", "run", "dev"]

  pigeonwarden-prod:
    build: .
    container_name: pigeonwarden-prod
    network_mode: "host"
    privileged: true
    devices:
      - /dev:/dev
    depends_on:
      - redis
    env_file:
      - .env.local
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UDEV=1
    command: ["python3", "-m", "pigeonwarden", "run", "deploy"]

  redis:
    image: redis:7
    container_name: pigeonwarden-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
